name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker Compose
      run: make setup
    
    - name: Execute tests
      run: make test
      
    - name: Run code style check
      run: make lint
