name: Laravel Tests on PR

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      run: docker-compose up -d --build
      
    - name: Install Composer dependencies
      run: docker-compose exec app composer install
      
    - name: Prepare environment
      run: |
        docker-compose exec app cp .env.example .env
        docker-compose exec app php artisan key:generate
        docker-compose exec app php artisan config:clear
      
    - name: Run migrations and seed
      run: docker-compose exec app php artisan migrate --seed
      
    - name: Execute PHPUnit tests
      run: docker-compose exec app php artisan test
      
    - name: Run PHPStan (optional)
      run: docker-compose exec app vendor/bin/phpstan analyse
      
    - name: Run Pest tests (if used)
      run: docker-compose exec app vendor/bin/pest
